export type SortDirection = 'asc' | 'desc';
export type SearchExecutionStatus = 'pending' | 'queued' | 'running' | 'completed' | 'partial_failure' | 'failed' | 'cancelled';
export type CheckType = 'leak_email' | 'leak_username' | 'leak_phone' | 'leak_domain' | 'password_hash' | 'image' | 'video' | 'source_only';
export type CheckStatus = SearchExecutionStatus;
export type AssetType = 'image' | 'video' | 'document' | 'other';
export type AssetStatus = 'pending_upload' | 'uploaded' | 'scanning' | 'ready' | 'flagged' | 'failed';
export type SourceType = 'profile_url' | 'listing_url' | 'image_url' | 'video_url' | 'document_url' | 'social_post_url' | 'other_url';
export type SourceValidationStatus = 'pending' | 'validated' | 'invalid' | 'rejected';
export type MatchType = 'exact_hash' | 'perceptual_hash' | 'face_match' | 'video_match' | 'text_match' | 'listing_match' | 'provider_hit' | 'manual_report';
export type WorkflowStatus = 'active' | 'completed' | 'cancelled';
export type WorkflowStepStatus = 'pending' | 'in_progress' | 'completed' | 'skipped' | 'blocked';
export type RemovalCaseType = 'privacy_removal' | 'non_consensual_intimate_content' | 'impersonation' | 'defamation' | 'copyright' | 'other';
export type ReviewType = 'analyst' | 'support_escalation' | 'removal_review';
export type ReviewPriority = 'low' | 'medium' | 'high' | 'urgent';
export type ReviewStatus = 'open' | 'triaged' | 'assigned' | 'in_review' | 'waiting_more_context' | 'decided' | 'escalated' | 'closed';
export type ReviewDecisionOutcome = 'no_evidence_of_manipulation' | 'suspicious_needs_monitoring' | 'likely_manipulated' | 'confirmed_known_fake' | 'insufficient_evidence' | 'no_match' | 'weak_candidate' | 'strong_candidate_reviewed' | 'insufficient_quality' | 'not_actionable' | 'monitor' | 'action_recommended' | 'removal_recommended';
export type RecommendedAction = 'monitor' | 'rerun_analysis' | 'request_more_context' | 'handover_support' | 'recommend_removal' | 'legal_escalation';
export type RemovalStatus = 'open' | 'preparing' | 'submitted' | 'under_review' | 'followup_required' | 'escalated' | 'removed' | 'partially_removed' | 'rejected' | 'closed';
export type RemovalActionType = 'email_notice' | 'webform_notice' | 'api_notice' | 'followup' | 'legal_escalation' | 'internal_note';
export type SupportRequestType = 'support' | 'removal' | 'upload_review' | 'identity_review';
export type SupportStatus = 'open' | 'triaged' | 'assigned' | 'in_progress' | 'waiting_user' | 'escalated' | 'resolved' | 'closed';
export type ProviderCategory = 'leak' | 'search' | 'social' | 'video' | 'image' | 'registry' | 'other';
export type ProviderStatus = 'active' | 'degraded' | 'disabled' | 'maintenance';
export type EvidenceCoverage = 'complete' | 'partial' | 'missing';
export type Severity = 'low' | 'medium' | 'high' | 'critical';
export type SlaRisk = 'healthy' | 'watch' | 'risk' | 'breach';
export type WorkflowStatusTone = 'neutral' | 'info' | 'success' | 'warning' | 'danger';
export type SearchQueryType = 'person' | 'asset' | 'url' | 'platform';
export type SearchCandidateType = 'profile' | 'listing' | 'image' | 'video' | 'document';
export type SearchRetrievalMethod = 'exact' | 'fuzzy' | 'embedding' | 'hybrid';
export type SearchSortField = 'updatedAt' | 'priority' | 'slaRisk' | 'score';
export type AssetRepresentationType = 'exact_hash' | 'phash' | 'embedding' | 'audio_fingerprint' | 'transcript' | 'ocr';
export type TextArtifactType = 'ocr' | 'transcript';
export type EvidenceSnapshotType = 'search_result' | 'review_brief' | 'provider_packet';
export type EvidenceSourceKind = 'url' | 'screenshot' | 'document' | 'audit_log';
export type EvidenceSourceStatus = 'verified' | 'pending' | 'missing';
export type StatusBadgeDefinition = {
    label: string;
    tone: WorkflowStatusTone;
};
export declare const statusToneClassNames: Record<WorkflowStatusTone, string>;
export declare const reviewPriorityBadgeMap: Record<ReviewPriority, StatusBadgeDefinition>;
export declare const supportStatusBadgeMap: Record<SupportStatus, StatusBadgeDefinition>;
export declare const reviewStatusBadgeMap: Record<ReviewStatus, StatusBadgeDefinition>;
export declare const removalStatusBadgeMap: Record<RemovalStatus, StatusBadgeDefinition>;
export declare const evidenceCoverageBadgeMap: Record<EvidenceCoverage, StatusBadgeDefinition>;
export declare const slaRiskBadgeMap: Record<SlaRisk, StatusBadgeDefinition>;
export declare const supportRequestTypeLabels: Record<SupportRequestType, string>;
export declare const severityTextClassNames: Record<Severity, string>;
