import type {
  AssetRecord,
  CheckRecord,
  ContentMatchRecord,
  EvidenceSnapshot,
  ProviderRecord,
  RemovalCaseRecord,
  ReviewQueueItem,
  SourceRecord,
  SupportQueueItem,
  SupportRequestRecord,
  UnifiedSearchRecord,
  WorkflowRecord,
} from './trustshield-records.js';

const sharedEvidenceSnapshots: Record<string, EvidenceSnapshot> = {
  'EV-1001': {
    id: 'EV-1001',
    snapshotType: 'provider_packet',
    summary: 'Primäre URL, Vollscreenshot und Audit-Historie liegen konsistent vor.',
    coverage: 'complete',
    retentionNote: 'Anhänge bis Provider-Antwort und Audit-Fenster vorhalten.',
    capturedAt: '2026-03-30T01:10:00Z',
    linkedAssetId: 'asset-berlin-image-1',
    linkedCheckId: 'check-image-1',
    linkedMatchId: 'match-whitepages-1',
    linkedReviewItemId: 'RV-3102',
    sources: [
      { id: 'SRC-1', label: 'Live-URL', kind: 'url', status: 'verified' },
      { id: 'SRC-2', label: 'Full-page Screenshot', kind: 'screenshot', status: 'verified' },
      { id: 'SRC-3', label: 'Audit Trail', kind: 'audit_log', status: 'verified' },
    ],
    evidence: {
      providerPacket: true,
      screenshots: 1,
      urlVerified: true,
    },
  },
  'EV-1002': {
    id: 'EV-1002',
    snapshotType: 'review_brief',
    summary: 'Treffer und Kontext sind sichtbar, Primärevidenz braucht aber Nachreichung.',
    coverage: 'partial',
    retentionNote: 'Nur minimierte Vorschaudaten bis zur Nachlieferung speichern.',
    capturedAt: '2026-03-30T00:20:00Z',
    linkedAssetId: 'asset-doc-1',
    linkedCheckId: 'check-source-1',
    linkedReviewItemId: 'RV-3018',
    sources: [
      { id: 'SRC-4', label: 'Match Preview', kind: 'document', status: 'verified' },
      { id: 'SRC-5', label: 'Timestamped Screenshot', kind: 'screenshot', status: 'pending' },
    ],
    evidence: {
      partialTimeline: true,
      awaitingPrimaryEvidence: true,
    },
  },
  'EV-1003': {
    id: 'EV-1003',
    snapshotType: 'search_result',
    summary: 'Operativer Treffer mit Eskalationsrelevanz, aber ohne belastbaren Primärbeleg.',
    coverage: 'missing',
    retentionNote: 'Sensible Hinweise nur rollenbasiert sichtbar machen.',
    capturedAt: '2026-03-29T23:55:00Z',
    linkedCheckId: 'check-platform-1',
    linkedMatchId: 'match-local-indexer-1',
    linkedReviewItemId: 'RV-2999',
    sources: [
      { id: 'SRC-6', label: 'Provider Response Stub', kind: 'document', status: 'pending' },
      { id: 'SRC-7', label: 'Original URL', kind: 'url', status: 'missing' },
    ],
    evidence: {
      escalationOnly: true,
      primaryEvidenceMissing: true,
    },
  },
};

export const mockProviders: ProviderRecord[] = [
  {
    id: 'provider-whitepages',
    slug: 'whitepages',
    displayName: 'Whitepages',
    category: 'search',
    status: 'active',
    capabilities: ['search', 'removal_submission', 'status_sync'],
    supportedSourceTypes: ['listing_url', 'profile_url'],
    supportsAsyncJobs: true,
    rateLimitPerMinute: 60,
    baseUrl: 'https://whitepages.example',
    documentationUrl: 'https://whitepages.example/docs',
    retentionHint: 'Provider packets nur bis Antwortfenster vorhalten.',
    summary: 'Primärer Personenverzeichnis-Provider für Removal und Lookup.',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-30T01:00:00Z',
  },
];

export const mockChecks: CheckRecord[] = [
  {
    id: 'check-image-1',
    type: 'image',
    status: 'completed',
    input: { assetId: 'asset-berlin-image-1', submittedSourceIds: ['source-whitepages-1'] },
    risk: { score: 91, severity: 'critical', rationale: 'Known leak + actionability', flaggedSignals: ['known_leak', 'public_indexed'] },
    submittedSourceIds: ['source-whitepages-1'],
    primaryAssetId: 'asset-berlin-image-1',
    workflowInstanceId: 'workflow-removal-1',
    supportRequestId: 'support-req-1',
    reviewItemIds: ['RV-3102'],
    removalCaseIds: ['RM-2041'],
    summary: 'Bildbasierter Check mit belastbarem Whitepages-Treffer.',
    createdAt: '2026-03-29T20:00:00Z',
    updatedAt: '2026-03-30T01:10:00Z',
  },
];

export const mockAssets: AssetRecord[] = [
  {
    id: 'asset-berlin-image-1',
    assetType: 'image',
    status: 'ready',
    originalFilename: 'berlin-profile.png',
    mimeType: 'image/png',
    fileSizeBytes: 2400000,
    sha256: 'sha256-example',
    dimensions: { width: 1440, height: 900 },
    storageKey: 'assets/2026/03/berlin-profile.png',
    ownerUserId: 'user-1',
    flags: { nsfw: false, sensitive: true, malwareScanned: true, malwareDetected: false },
    primaryCheckId: 'check-image-1',
    representationIds: ['repr-1'],
    sourceIds: ['source-whitepages-1'],
    summary: 'Screenshot eines indexierten Profils.',
    createdAt: '2026-03-29T19:55:00Z',
    updatedAt: '2026-03-29T19:58:00Z',
  },
];

export const mockSources: SourceRecord[] = [
  {
    id: 'source-whitepages-1',
    sourceType: 'listing_url',
    sourceUrl: 'https://whitepages.com/profile/jane-doe-berlin',
    sourceDomain: 'whitepages.com',
    platformName: 'Whitepages',
    pageTitle: 'Jane Doe Berlin',
    notes: 'Vom Nutzer gemeldete öffentliche Listing-URL.',
    validationStatus: 'validated',
    assetId: 'asset-berlin-image-1',
    checkId: 'check-image-1',
    submittedByUserId: 'user-1',
    summary: 'Validierte Listing-URL mit hohem Removal-Potenzial.',
    createdAt: '2026-03-29T19:56:00Z',
    updatedAt: '2026-03-29T20:05:00Z',
  },
];

export const mockContentMatches: ContentMatchRecord[] = [
  {
    id: 'match-whitepages-1',
    assetId: 'asset-berlin-image-1',
    checkId: 'check-image-1',
    sourceId: 'source-whitepages-1',
    providerId: 'provider-whitepages',
    matchType: 'listing_match',
    matchedUrl: 'https://whitepages.com/profile/jane-doe-berlin',
    platformName: 'Whitepages',
    firstSeenAt: '2026-03-29T20:02:00Z',
    lastSeenAt: '2026-03-30T01:10:00Z',
    confidence: 0.97,
    knownFake: false,
    knownLeak: true,
    active: true,
    reviewItemId: 'RV-3102',
    removalCaseId: 'RM-2041',
    summary: 'Bestätigtes Listing-Match mit hoher Confidence.',
    createdAt: '2026-03-29T20:02:00Z',
    updatedAt: '2026-03-30T01:10:00Z',
  },
];

export const mockWorkflows: WorkflowRecord[] = [
  {
    id: 'workflow-removal-1',
    workflowId: 'wf-removal-default',
    checkId: 'check-image-1',
    status: 'active',
    currentStepIndex: 1,
    steps: [
      {
        id: 'wf-step-1',
        workflowStepId: 'capture-evidence',
        status: 'completed',
        title: 'Evidenz erfassen',
        description: 'Primäre URL und Screenshot sichern.',
        requiresConfirmation: true,
        supportHandoverPossible: false,
        updatedAt: '2026-03-29T20:10:00Z',
      },
      {
        id: 'wf-step-2',
        workflowStepId: 'prepare-removal',
        status: 'in_progress',
        title: 'Removal vorbereiten',
        description: 'Provider-Rückfrage beantworten.',
        requiresConfirmation: true,
        supportHandoverPossible: true,
        updatedAt: '2026-03-30T01:15:00Z',
      },
    ],
    createdAt: '2026-03-29T20:05:00Z',
    updatedAt: '2026-03-30T01:15:00Z',
  },
];

export const mockSupportRequests: SupportRequestRecord[] = [
  {
    id: 'support-req-1',
    requestType: 'removal',
    priority: 'urgent',
    status: 'open',
    preferredContact: 'email',
    message: 'Bitte Removal möglichst sofort anstoßen.',
    checkId: 'check-image-1',
    assetId: 'asset-berlin-image-1',
    removalCaseId: 'RM-2041',
    assignedTo: 'Anna K.',
    assignmentHistory: [
      {
        assignedTo: 'Anna K.',
        assignedBy: 'system-seed',
        reason: 'Initiale Queue-Zuweisung',
        changedAt: '2026-03-29T20:10:00Z',
      },
    ],
    statusHistory: [
      {
        toStatus: 'open',
        changedBy: 'system-seed',
        reason: 'Initialer Seed-Status',
        changedAt: '2026-03-29T20:07:00Z',
      },
    ],
    audit: {
      createdBy: 'system-seed',
      lastModifiedBy: 'system-seed',
      lastAction: 'seeded',
    },
    retention: {
      policyKey: 'support-request-default',
      retainUntil: '2027-03-29T20:07:00Z',
      lastReviewedAt: '2026-03-30T01:12:00Z',
    },
    createdAt: '2026-03-29T20:07:00Z',
    updatedAt: '2026-03-30T01:12:00Z',
  },
];

export const mockReviewQueue: ReviewQueueItem[] = [
  {
    id: 'RV-3102',
    reviewType: 'removal_review',
    priority: 'urgent',
    status: 'in_review',
    assignedTo: 'Anna K.',
    linkedRemovalCaseId: 'RM-2041',
    linkedCheckId: 'check-image-1',
    linkedAssetId: 'asset-berlin-image-1',
    linkedMatchId: 'match-whitepages-1',
    summary: 'Provider fordert zusätzliche Kontextzeile zur öffentlichen Indexierung an.',
    recommendedAction: 'recommend_removal',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1001'],
    createdAt: '2026-03-29T21:15:00Z',
    updatedAt: '2026-03-30T01:18:00Z',
  },
  {
    id: 'RV-3018',
    reviewType: 'support_escalation',
    priority: 'high',
    status: 'waiting_more_context',
    assignedTo: 'Murat S.',
    linkedSupportRequestId: 'US-7610',
    linkedCheckId: 'check-source-1',
    summary: 'Identitätsreview blockiert durch fehlende Primärevidenz.',
    recommendedAction: 'request_more_context',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1002'],
    createdAt: '2026-03-29T19:40:00Z',
    updatedAt: '2026-03-30T00:22:00Z',
  },
  {
    id: 'RV-2999',
    reviewType: 'analyst',
    priority: 'high',
    status: 'escalated',
    assignedTo: 'Legal Desk',
    linkedRemovalCaseId: 'RM-1762',
    linkedSupportRequestId: 'US-6451',
    linkedMatchId: 'match-local-indexer-1',
    summary: 'Wiederveröffentlichung mit hoher Actionability und sensibler Evidenz.',
    recommendedAction: 'legal_escalation',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1003'],
    finalDecision: 'removal_recommended',
    createdAt: '2026-03-29T18:05:00Z',
    updatedAt: '2026-03-29T23:58:00Z',
  },
];

export const mockUnifiedSearchRecords: UnifiedSearchRecord[] = [
  {
    id: 'SR-4401',
    title: 'Whitepages Berlin listing',
    platform: 'Whitepages',
    queryType: 'url',
    searchStatus: 'completed',
    reviewPriority: 'urgent',
    reviewStatus: 'in_review',
    removalStatus: 'under_review',
    supportStatus: 'open',
    evidenceCoverage: 'complete',
    severity: 'high',
    slaRisk: 'risk',
    assignedTo: 'Anna K.',
    linkedCheckId: 'check-image-1',
    linkedAssetId: 'asset-berlin-image-1',
    linkedRemovalCaseId: 'RM-2041',
    linkedSupportRequestId: 'support-req-1',
    summary: 'Öffentlich indexiertes Profil mit belastbarer URL-, Screenshot- und Audit-Basis.',
    createdAt: '2026-03-29T20:02:00Z',
    updatedAt: 'Vor 5 Stunden',
    nextActionLabel: 'Provider-Rückfrage beantworten',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1001'],
    candidates: [
      {
        id: 'SC-11',
        candidateUrl: 'whitepages.com/profile/jane-doe-berlin',
        candidateSource: 'Search index',
        candidateType: 'listing',
        retrievalMethod: 'hybrid',
        rawScore: 0.92,
        rerankedScore: 0.97,
        rankPosition: 1,
        promotedToMatch: true,
      },
    ],
  },
  {
    id: 'SR-4402',
    title: 'Archivmirror Personenprofil',
    platform: 'Archivmirror',
    queryType: 'person',
    searchStatus: 'partial_failure',
    reviewPriority: 'high',
    reviewStatus: 'waiting_more_context',
    removalStatus: 'followup_required',
    supportStatus: 'waiting_user',
    evidenceCoverage: 'partial',
    severity: 'high',
    slaRisk: 'watch',
    assignedTo: 'Offen',
    linkedCheckId: 'check-source-1',
    summary: 'Treffer ist plausibel, aber Primärevidenz und Zeitstempel sind unvollständig.',
    createdAt: '2026-03-29T21:10:00Z',
    updatedAt: 'Vor 2 Stunden',
    nextActionLabel: 'Vollscreenshot mit Zeitstempel anfordern',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1002'],
    candidates: [
      {
        id: 'SC-12',
        candidateUrl: 'archive.example.org/personenprofil-2018',
        candidateSource: 'Archive crawl',
        candidateType: 'profile',
        retrievalMethod: 'embedding',
        rawScore: 0.74,
        rerankedScore: 0.8,
        rankPosition: 2,
        promotedToMatch: false,
      },
    ],
  },
  {
    id: 'SR-4403',
    title: 'Local Indexer Republishing',
    platform: 'Local Indexer',
    queryType: 'platform',
    searchStatus: 'queued',
    reviewPriority: 'high',
    reviewStatus: 'escalated',
    removalStatus: 'escalated',
    supportStatus: 'escalated',
    evidenceCoverage: 'missing',
    severity: 'high',
    slaRisk: 'breach',
    assignedTo: 'Legal Desk',
    linkedCheckId: 'check-platform-1',
    linkedRemovalCaseId: 'RM-1762',
    linkedSupportRequestId: 'US-6451',
    summary: 'Wiederveröffentlichung ist operativ relevant, belastbare Primärevidenz fehlt noch.',
    createdAt: '2026-03-29T23:20:00Z',
    updatedAt: 'Vor 24 Minuten',
    nextActionLabel: 'Eskalationspfad mit Legal abstimmen',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1003'],
    candidates: [
      {
        id: 'SC-13',
        candidateUrl: 'peoplefinder.example.net/listing/20499',
        candidateSource: 'Provider watchlist',
        candidateType: 'listing',
        retrievalMethod: 'fuzzy',
        rawScore: 0.68,
        rerankedScore: 0.72,
        rankPosition: 1,
        promotedToMatch: false,
      },
    ],
  },
];

export const mockSupportQueue: SupportQueueItem[] = [
  {
    id: 'US-9921',
    requesterLabel: 'Privatperson · archivierter Leak',
    priority: 'urgent',
    requestType: 'removal',
    status: 'open',
    assignedTo: 'Anna K.',
    slaRisk: 'risk',
    slaDueAt: '02:15 h verbleibend',
    updatedAt: 'Vor 8 Minuten',
    note: 'PII inklusive Wohnort öffentlich indexiert.',
    linkedReviewItemId: 'RV-3102',
    linkedRemovalCaseId: 'RM-2041',
    evidenceCoverage: 'complete',
  },
  {
    id: 'US-8842',
    requesterLabel: 'Creator Support · Plattform-Eskalation',
    priority: 'high',
    requestType: 'support',
    status: 'assigned',
    assignedTo: 'Murat S.',
    slaRisk: 'watch',
    slaDueAt: 'Heute, 14:30',
    updatedAt: 'Vor 31 Minuten',
    note: 'Nutzer wartet auf Rückmeldung zur Provider-Antwort.',
    evidenceCoverage: 'complete',
  },
  {
    id: 'US-7610',
    requesterLabel: 'Identitätsprüfung · Dokumentenreview',
    priority: 'medium',
    requestType: 'identity_review',
    status: 'waiting_user',
    assignedTo: 'Offen',
    slaRisk: 'healthy',
    slaDueAt: 'Warten auf Upload',
    updatedAt: 'Vor 2 Stunden',
    note: 'Sekundärevidenz vorhanden, Primärnachweis fehlt.',
    linkedReviewItemId: 'RV-3018',
    evidenceCoverage: 'partial',
  },
  {
    id: 'US-6451',
    requesterLabel: 'Upload Review · Deepfake-Hinweis',
    priority: 'high',
    requestType: 'upload_review',
    status: 'escalated',
    assignedTo: 'Legal Desk',
    slaRisk: 'breach',
    slaDueAt: 'Überfällig seit 45 Min.',
    updatedAt: 'Vor 12 Minuten',
    note: 'Sicherheitsrelevanter Fund mit Eskalationspfad aktiv.',
    linkedReviewItemId: 'RV-2999',
    linkedRemovalCaseId: 'RM-1762',
    evidenceCoverage: 'missing',
  },
];

export const mockRemovalCases: RemovalCaseRecord[] = [
  {
    id: 'RM-2041',
    caseType: 'privacy_removal',
    platform: 'Whitepages',
    targetUrl: 'https://whitepages.com/profile/jane-doe-berlin',
    legalBasis: 'DSGVO Art. 17',
    status: 'under_review',
    severity: 'high',
    evidenceCoverage: 'complete',
    slaRisk: 'risk',
    reviewStatus: 'in_review',
    supportRequested: true,
    assignedTo: 'Anna K.',
    linkedAssetId: 'asset-berlin-image-1',
    linkedMatchId: 'match-whitepages-1',
    linkedCheckId: 'check-image-1',
    createdAt: '2026-03-29T20:15:00Z',
    updatedAt: '2026-03-30T01:18:00Z',
    lastUpdateAt: 'Vor 5 Stunden',
    nextActionLabel: 'Provider-Rückfrage beantworten',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1001'],
    actions: [{ id: 'act-1', actionType: 'webform_notice', recipient: 'Whitepages', payloadSummary: 'Removal-Fall eingereicht', resultStatus: 'submitted', externalTicketId: 'WHT-991', createdAt: '2026-03-29T20:20:00Z' }],
  },
  {
    id: 'RM-1984',
    caseType: 'privacy_removal',
    platform: 'Spokeo',
    targetUrl: 'https://spokeo.com/identity/berlin-jd-9284',
    legalBasis: 'DSGVO Art. 17',
    status: 'submitted',
    severity: 'medium',
    evidenceCoverage: 'complete',
    slaRisk: 'healthy',
    reviewStatus: 'assigned',
    supportRequested: false,
    assignedTo: 'Murat S.',
    createdAt: '2026-03-29T10:10:00Z',
    updatedAt: '2026-03-29T18:40:00Z',
    lastUpdateAt: 'Gestern, 18:40',
    nextActionLabel: 'Wartefenster beobachten',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1001'],
    actions: [{ id: 'act-2', actionType: 'email_notice', recipient: 'Spokeo', payloadSummary: 'Erstmeldung', resultStatus: 'submitted', externalTicketId: 'SPK-443', createdAt: '2026-03-29T10:15:00Z' }],
  },
  {
    id: 'RM-1877',
    caseType: 'other',
    platform: 'Archivmirror',
    targetUrl: 'https://archive.example.org/personenprofil-2018',
    status: 'followup_required',
    severity: 'high',
    evidenceCoverage: 'partial',
    slaRisk: 'watch',
    reviewStatus: 'waiting_more_context',
    supportRequested: true,
    assignedTo: 'Offen',
    createdAt: '2026-03-29T17:20:00Z',
    updatedAt: '2026-03-30T00:22:00Z',
    lastUpdateAt: 'Vor 2 Stunden',
    nextActionLabel: 'Vollscreenshot mit Zeitstempel anfordern',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1002'],
    actions: [],
  },
  {
    id: 'RM-1762',
    caseType: 'non_consensual_intimate_content',
    platform: 'Local Indexer',
    targetUrl: 'https://peoplefinder.example.net/listing/20499',
    status: 'escalated',
    severity: 'high',
    evidenceCoverage: 'missing',
    slaRisk: 'breach',
    reviewStatus: 'escalated',
    supportRequested: true,
    assignedTo: 'Legal Desk',
    createdAt: '2026-03-29T23:40:00Z',
    updatedAt: '2026-03-29T23:58:00Z',
    lastUpdateAt: 'Vor 24 Minuten',
    nextActionLabel: 'Eskalationspfad mit Legal abstimmen',
    evidenceSnapshot: sharedEvidenceSnapshots['EV-1003'],
    actions: [{ id: 'act-3', actionType: 'legal_escalation', recipient: 'Legal Desk', payloadSummary: 'Externer Eskalationspfad', resultStatus: 'active', createdAt: '2026-03-29T23:50:00Z' }],
  },
];
