import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { evidenceCoverageBadgeMap, removalStatusBadgeMap, reviewPriorityBadgeMap, reviewStatusBadgeMap, severityTextClassNames, slaRiskBadgeMap, supportRequestTypeLabels, supportStatusBadgeMap } from '@trustshield/core';
import { StatusBadge } from './components';
import { cn } from './index';
export function FeatureCard({ className, ...props }) { return _jsx("div", { className: cn('rounded-[1.5rem] bg-white/85 p-4', className), ...props }); }
const rbacToneClassNames = {
    default: 'bg-[#eef3fb] text-[#094cb2]',
    warning: 'bg-[#f6ede9] text-[#8a4b22]',
    critical: 'bg-[#fbefee] text-[#a0362f]',
};
export function EvidenceSnapshotCard({ snapshot, className }) {
    return _jsxs(FeatureCard, { className: cn('space-y-3', className), children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [_jsx(StatusBadge, { definition: evidenceCoverageBadgeMap[snapshot.coverage] }), _jsx("span", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: snapshot.snapshotType })] }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: snapshot.summary }), _jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: snapshot.retentionNote })] });
}
export function RbacScopeBadge({ label, scope, emphasis = 'default', className }) {
    return _jsxs("div", { className: cn('rounded-[1.25rem] p-4', rbacToneClassNames[emphasis], className), children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em]", children: label }), _jsx("p", { className: "mt-2 font-[family-name:var(--font-body)] text-sm leading-6", children: scope })] });
}
export function AuditRetentionPanel({ label, auditEvent, retention, className }) {
    return _jsxs("div", { className: cn('rounded-[1.25rem] bg-white/85 p-4', className), children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: label }), _jsx("p", { className: "mt-2 font-[family-name:var(--font-heading)] text-sm text-stone-950", children: auditEvent }), _jsx("p", { className: "mt-2 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700", children: retention })] });
}
export function ReviewOutcomeActionCard({ outcome, actionLabel, rbacScope, auditEvent, retention, rbacLabel = 'RBAC-Scope', auditLabel = 'Audit & Retention', emphasis = 'default', className, badgeClassName }) {
    return _jsxs(FeatureCard, { className: cn('space-y-4 bg-[#f8f5ef]', className), children: [_jsxs("div", { className: "flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "font-[family-name:var(--font-heading)] text-lg text-stone-950", children: actionLabel }), _jsxs("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: ["Outcome: ", outcome] })] }), _jsx("span", { className: cn('inline-flex items-center rounded-full px-3 py-1 font-[family-name:var(--font-label)] text-[11px] font-semibold uppercase tracking-[0.16em]', badgeClassName ?? 'bg-[#eef3fb] text-[#094cb2]'), children: auditEvent })] }), _jsxs("div", { className: "grid gap-3 lg:grid-cols-2", children: [_jsx(RbacScopeBadge, { label: rbacLabel, scope: rbacScope, emphasis: emphasis }), _jsx(AuditRetentionPanel, { label: auditLabel, auditEvent: auditEvent, retention: retention })] })] });
}
export function RemovalCaseFlowCard({ item, className }) {
    return _jsxs(FeatureCard, { className: cn('space-y-4 bg-white', className), children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [_jsx("span", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: item.id }), _jsx(StatusBadge, { definition: removalStatusBadgeMap[item.status] }), _jsx(StatusBadge, { definition: evidenceCoverageBadgeMap[item.evidenceCoverage] }), _jsx(StatusBadge, { definition: slaRiskBadgeMap[item.slaRisk] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "font-[family-name:var(--font-heading)] text-lg text-stone-950", children: item.platform }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: item.nextActionLabel })] }), _jsxs("div", { className: "grid gap-3 sm:grid-cols-2", children: [_jsxs("div", { className: "rounded-[1.25rem] bg-[#f8f5ef] p-4", children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: "Zust\u00E4ndigkeit" }), _jsx("p", { className: "mt-2 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700", children: item.assignedTo ?? 'Nicht zugewiesen' })] }), _jsxs("div", { className: "rounded-[1.25rem] bg-[#f8f5ef] p-4", children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: "Retention" }), _jsx("p", { className: "mt-2 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700", children: item.evidenceSnapshot.retentionNote })] })] })] });
}
export function IntakeErrorPanel({ title, summary, items, className }) {
    return _jsxs(FeatureCard, { className: cn('space-y-4 bg-[#fbefee]', className), children: [_jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-[#a0362f]", children: "Fehlerpfad" }), _jsx("p", { className: "font-[family-name:var(--font-heading)] text-lg text-stone-950", children: title }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700", children: summary })] }), _jsx("div", { className: "space-y-3", children: items.map((item) => _jsxs("div", { className: "rounded-[1.25rem] bg-white/80 p-4", children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: item.label }), _jsx("p", { className: "mt-2 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700", children: item.detail })] }, item.label)) })] });
}
export function ValidationIssueList({ issues, className, itemClassName, pathClassName, emptyLabel = 'Keine Fehler erkannt' }) {
    if (issues.length === 0) {
        return _jsx("p", { className: cn('font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600', className), children: emptyLabel });
    }
    return _jsx("ul", { className: cn('space-y-2 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700', className), children: issues.map((issue, index) => _jsxs("li", { className: itemClassName, children: [_jsx("span", { className: cn('font-semibold text-stone-900', pathClassName), children: issue.path || 'root' }), ' · ', issue.message] }, `${issue.path ?? 'root'}:${issue.message}:${index}`)) });
}
export function RbacAuditHintCard({ title, description, rbacLabel = 'RBAC-Scope', rbacScope, auditLabel = 'Audit & Retention', auditEvent, retention, emphasis = 'default', className, panelClassName }) {
    return _jsxs(FeatureCard, { className: cn('space-y-4 bg-[#f8f5ef]', className), children: [_jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "font-[family-name:var(--font-heading)] text-lg text-stone-950", children: title }), description ? _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: description }) : null] }), _jsxs("div", { className: cn('grid gap-3 lg:grid-cols-2', panelClassName), children: [_jsx(RbacScopeBadge, { label: rbacLabel, scope: rbacScope, emphasis: emphasis }), _jsx(AuditRetentionPanel, { label: auditLabel, auditEvent: auditEvent, retention: retention })] })] });
}
export function ReviewSummaryCard({ item, className }) {
    return _jsxs(FeatureCard, { className: cn('space-y-3 bg-[#f8f5ef]', className), children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [_jsx("span", { className: "font-[family-name:var(--font-label)] text-xs font-semibold uppercase tracking-[0.18em] text-stone-500", children: item.id }), _jsx(StatusBadge, { definition: reviewPriorityBadgeMap[item.priority] }), _jsx(StatusBadge, { definition: reviewStatusBadgeMap[item.status] }), _jsx(StatusBadge, { definition: evidenceCoverageBadgeMap[item.evidenceSnapshot.coverage] })] }), _jsx("p", { className: "font-[family-name:var(--font-heading)] text-lg text-stone-950", children: item.summary }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: item.recommendedAction }), _jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: item.evidenceSnapshot.summary })] });
}
export function SupportQueueRow({ item }) {
    return _jsxs("tr", { className: "align-top", children: [_jsx("td", { className: "px-4 py-4", children: _jsxs("div", { className: "rounded-[1.5rem] bg-white p-4", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsxs("span", { className: "font-[family-name:var(--font-label)] text-sm font-semibold tracking-[0.08em] text-[#094cb2]", children: ["#", item.id] }), _jsx("span", { className: "font-[family-name:var(--font-body)] text-sm text-stone-600", children: item.updatedAt })] }), _jsx("p", { className: "mt-3 font-[family-name:var(--font-heading)] text-lg text-stone-950", children: item.requesterLabel }), _jsx("p", { className: "mt-2 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: item.note })] }) }), _jsx("td", { className: "px-4 py-4", children: _jsx(StatusBadge, { definition: reviewPriorityBadgeMap[item.priority] }) }), _jsx("td", { className: "px-4 py-4 font-[family-name:var(--font-body)] text-sm text-stone-700", children: supportRequestTypeLabels[item.requestType] }), _jsx("td", { className: "px-4 py-4", children: _jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsx(StatusBadge, { definition: supportStatusBadgeMap[item.status] }), _jsx(StatusBadge, { definition: slaRiskBadgeMap[item.slaRisk] }), _jsx(StatusBadge, { definition: evidenceCoverageBadgeMap[item.evidenceCoverage] })] }) }), _jsx("td", { className: "px-4 py-4", children: _jsxs("div", { className: "space-y-3 rounded-[1.5rem] bg-[#f1ece2] p-4", children: [_jsx("p", { className: "font-[family-name:var(--font-body)] text-sm text-stone-700", children: item.assignedTo }), _jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: item.slaDueAt }), _jsx("button", { className: "font-[family-name:var(--font-label)] text-xs font-semibold uppercase tracking-[0.18em] text-[#094cb2] underline-offset-4 hover:underline", children: "Fall \u00F6ffnen" })] }) })] });
}
export function RemovalCaseRow({ item }) {
    return _jsxs("div", { className: "grid gap-4 rounded-[1.75rem] bg-[#f8f5ef] p-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)_minmax(12rem,0.8fr)]", children: [_jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsx("span", { className: "font-[family-name:var(--font-label)] text-xs font-semibold uppercase tracking-[0.18em] text-stone-500", children: item.id }), _jsxs("span", { className: cn('font-[family-name:var(--font-label)] text-xs font-semibold uppercase tracking-[0.18em]', severityTextClassNames[item.severity]), children: [item.severity, " severity"] })] }), _jsx("h3", { className: "font-[family-name:var(--font-heading)] text-2xl text-stone-950", children: item.platform }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-[#094cb2] underline decoration-[#094cb2]/30 underline-offset-4", children: item.targetUrl })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsx(StatusBadge, { definition: removalStatusBadgeMap[item.status] }), _jsx(StatusBadge, { definition: evidenceCoverageBadgeMap[item.evidenceCoverage] }), _jsx(StatusBadge, { definition: slaRiskBadgeMap[item.slaRisk] }), _jsx(StatusBadge, { definition: reviewStatusBadgeMap[item.reviewStatus] })] }), _jsxs("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: ["Letztes Update: ", item.lastUpdateAt] })] }), _jsxs("div", { className: "rounded-[1.5rem] bg-white p-4", children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: "N\u00E4chste Aktion" }), _jsx("p", { className: "mt-3 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700", children: item.nextActionLabel }), _jsx("button", { className: "mt-4 font-[family-name:var(--font-label)] text-xs font-semibold uppercase tracking-[0.18em] text-[#094cb2] underline-offset-4 hover:underline", children: "Falldetails \u00F6ffnen" })] })] });
}
export function SearchEvidenceCard({ record, className }) {
    return _jsxs(FeatureCard, { className: cn('space-y-2', className), children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [_jsx("span", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: record.id }), _jsx(StatusBadge, { definition: evidenceCoverageBadgeMap[record.evidenceCoverage] }), _jsx(StatusBadge, { definition: reviewStatusBadgeMap[record.reviewStatus] })] }), _jsx("p", { className: "font-[family-name:var(--font-heading)] text-base text-stone-950", children: record.title }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: record.evidenceSnapshot.summary })] });
}
export function SearchResultCard({ record, className }) {
    return _jsxs(FeatureCard, { className: cn('space-y-4 bg-[#f8f5ef]', className), children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [_jsx("span", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: record.platform }), _jsx(StatusBadge, { definition: reviewPriorityBadgeMap[record.reviewPriority] }), _jsx(StatusBadge, { definition: reviewStatusBadgeMap[record.reviewStatus] }), _jsx(StatusBadge, { definition: evidenceCoverageBadgeMap[record.evidenceCoverage] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "font-[family-name:var(--font-heading)] text-lg text-stone-950", children: record.title }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: record.summary })] }), _jsxs("div", { className: "rounded-[1.25rem] bg-white/90 p-4", children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: "N\u00E4chste Aktion" }), _jsx("p", { className: "mt-2 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700", children: record.nextActionLabel })] })] });
}
export function ReviewDecisionCard({ item, className }) {
    return _jsxs(FeatureCard, { className: cn('space-y-4 bg-white', className), children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [_jsx("span", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: item.id }), _jsx(StatusBadge, { definition: reviewPriorityBadgeMap[item.priority] }), _jsx(StatusBadge, { definition: reviewStatusBadgeMap[item.status] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "font-[family-name:var(--font-heading)] text-lg text-stone-950", children: item.summary }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: item.recommendedAction })] }), _jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: item.evidenceSnapshot.retentionNote })] });
}
export function ReviewOutcomeActionList({ items, className, itemClassName, badgeClassNames }) {
    return _jsx("div", { className: cn('space-y-3', className), children: items.map((item, index) => _jsx(ReviewOutcomeActionCard, { ...item, className: cn(item.className, itemClassName), badgeClassName: item.badgeClassName ?? badgeClassNames?.[index % badgeClassNames.length] }, item.auditEvent)) });
}
export function ReviewOutcomeActionPanel({ title, description, items, className, listClassName, itemClassName, badgeClassNames }) {
    return _jsxs(FeatureCard, { className: cn('space-y-5 bg-white/85', className), children: [_jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "font-[family-name:var(--font-heading)] text-lg text-stone-950", children: title }), _jsx("p", { className: "font-[family-name:var(--font-body)] text-sm leading-6 text-stone-600", children: description })] }), _jsx(ReviewOutcomeActionList, { items: items, className: listClassName, itemClassName: itemClassName, badgeClassNames: badgeClassNames })] });
}
export function ReviewOutcomeGuidanceCard({ title, items, className }) {
    return _jsxs(FeatureCard, { className: cn('space-y-4 bg-white/85', className), children: [_jsx("p", { className: "font-[family-name:var(--font-label)] text-[11px] uppercase tracking-[0.18em] text-stone-500", children: title }), _jsx("ul", { className: "space-y-1 font-[family-name:var(--font-body)] text-sm leading-6 text-stone-700", children: items.map((item) => _jsx("li", { children: item }, item)) })] });
}
