#!/usr/bin/env python3
"""
API Registration & Configuration Helper
Automates as much as possible and guides through manual steps
"""

import os
import sys
import subprocess
import json
import time
from pathlib import Path
from typing import Optional, Dict
import requests

# Color codes
GREEN = '\033[92m'
RED = '\033[91m'
YELLOW = '\033[93m'
BLUE = '\033[94m'
RESET = '\033[0m'

class APIRegistrationHelper:
    def __init__(self):
        self.workspace_root = Path(__file__).parent.parent
        self.env_file = self.workspace_root / ".env.local"
        self.env_vars = self.load_env()
        self.email = "raut.deepakdesign@gmail.com"
        
    def load_env(self) -> Dict[str, str]:
        """Load existing .env.local or create empty dict"""
        if self.env_file.exists():
            env = {}
            with open(self.env_file) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#'):
                        key, _, val = line.partition('=')
                        env[key] = val
            return env
        return {}
    
    def save_env(self):
        """Save env vars to .env.local"""
        with open(self.env_file, 'w') as f:
            f.write(f"# Generated by register-apis.py\n")
            f.write(f"# Email: {self.email}\n")
            f.write(f"# Last updated: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            
            # Group by category
            sections = {
                'API Keys': {},
                'Feature Flags': {},
                'Rate Limiting': {},
            }
            
            for key, val in sorted(self.env_vars.items()):
                if key.endswith('_KEY') or key.endswith('_TOKEN') or key.endswith('_ID'):
                    sections['API Keys'][key] = val
                elif key.startswith('FEATURE_'):
                    sections['Feature Flags'][key] = val
                elif 'RATE' in key or 'QUOTA' in key or 'LIMIT' in key:
                    sections['Rate Limiting'][key] = val
            
            for section, items in sections.items():
                if items:
                    f.write(f"\n# ========== {section} ==========\n")
                    for key, val in sorted(items.items()):
                        f.write(f"{key}={val}\n")
    
    def print_header(self, text: str):
        """Print section header"""
        print(f"\n{BLUE}{'='*60}{RESET}")
        print(f"{BLUE}{text:^60}{RESET}")
        print(f"{BLUE}{'='*60}{RESET}\n")
    
    def print_status(self, api: str, status: str, color: str):
        """Print API status"""
        print(f"{color}  {api:<30} {status}{RESET}")
    
    def verify_huggingface(self, token: str) -> bool:
        """Verify Hugging Face token"""
        try:
            resp = requests.get(
                'https://huggingface.co/api/whoami',
                headers={'Authorization': f'Bearer {token}'},
                timeout=5
            )
            return resp.status_code == 200
        except:
            return False
    
    def step_1_huggingface(self):
        """Hugging Face registration (CRITICAL)"""
        self.print_header("Step 1: Hugging Face (CRITICAL - 2 minutes)")
        
        print(f"{YELLOW}🔗 Open this link in your browser:{RESET}")
        print(f"   https://huggingface.co/settings/tokens\n")
        
        print(f"📋 {YELLOW}Instructions:{RESET}")
        print(f"   1. Login with: {self.email}")
        print(f"   2. Click 'New token'")
        print(f"   3. Name: yourefuture-mvp")
        print(f"   4. Type: read")
        print(f"   5. Click 'Create token'")
        print(f"   6. Copy the token (starts with 'hf_')\n")
        
        token = input(f"{BLUE}Paste your Hugging Face token: {RESET}").strip()
        
        if not token:
            print(f"{RED}❌ Token required!{RESET}")
            return False
        
        print(f"\n{YELLOW}⏳ Verifying token...{RESET}")
        if self.verify_huggingface(token):
            self.env_vars['HUGGINGFACE_API_KEY'] = token
            print(f"{GREEN}✅ Token verified successfully!{RESET}")
            return True
        else:
            print(f"{RED}❌ Token verification failed. Check token and try again.{RESET}")
            return False
    
    def step_2_google_cloud(self):
        """Google Cloud Vision registration (RECOMMENDED)"""
        self.print_header("Step 2: Google Cloud Vision (10 minutes)")
        
        print(f"{YELLOW}🔗 Open this link:{RESET}")
        print(f"   https://console.cloud.google.com\n")
        
        print(f"📋 {YELLOW}Quick Setup:{RESET}")
        print(f"   1. Create new project: 'yourefuture-mvp'")
        print(f"   2. Search for 'Vision API' and enable it")
        print(f"   3. Go to Service Accounts: https://console.cloud.google.com/iam-admin/serviceaccounts")
        print(f"   4. Create service account: 'yourefuture-vision'")
        print(f"   5. Add role: Editor")
        print(f"   6. Create JSON key and download")
        print(f"   7. Save the file as: google-cloud-key.json\n")
        
        key_path = input(f"{BLUE}Path to google-cloud-key.json: {RESET}").strip()
        
        if not key_path or not os.path.exists(key_path):
            print(f"{RED}❌ File not found!{RESET}")
            return False
        
        try:
            with open(key_path) as f:
                creds = json.load(f)
            
            self.env_vars['GOOGLE_CLOUD_PROJECT_ID'] = creds['project_id']
            self.env_vars['GOOGLE_CLOUD_API_KEY_PATH'] = os.path.abspath(key_path)
            
            # Copy key file to secure location
            dest_path = self.workspace_root / '.secrets' / 'google-cloud-key.json'
            dest_path.parent.mkdir(exist_ok=True)
            with open(dest_path, 'w') as f:
                json.dump(creds, f)
            
            self.env_vars['GOOGLE_CLOUD_API_KEY_PATH'] = str(dest_path)
            
            print(f"{GREEN}✅ Google Cloud credentials saved!{RESET}")
            return True
        except Exception as e:
            print(f"{RED}❌ Error reading file: {e}{RESET}")
            return False
    
    def step_3_aws(self):
        """AWS Rekognition registration (OPTIONAL)"""
        self.print_header("Step 3: AWS Rekognition (15 minutes - OPTIONAL)")
        
        print(f"{YELLOW}🔗 Open this link:{RESET}")
        print(f"   https://aws.amazon.com/free\n")
        
        print(f"📋 {YELLOW}Quick Setup:{RESET}")
        print(f"   1. Sign up with: {self.email}")
        print(f"   2. Add payment method (free tier is fully free)")
        print(f"   3. Go to IAM: https://console.aws.amazon.com/iam/home")
        print(f"   4. Create user: yourefuture-mvp")
        print(f"   5. Attach policy: AmazonRekognitionReadOnlyAccess")
        print(f"   6. Create access key")
        print(f"   7. Copy Access Key ID and Secret Access Key\n")
        
        access_key = input(f"{BLUE}AWS Access Key ID: {RESET}").strip()
        secret_key = input(f"{BLUE}AWS Secret Access Key: {RESET}").strip()
        
        if access_key and secret_key:
            self.env_vars['AWS_ACCESS_KEY_ID'] = access_key
            self.env_vars['AWS_SECRET_ACCESS_KEY'] = secret_key
            self.env_vars['AWS_REGION'] = 'us-east-1'
            print(f"{GREEN}✅ AWS credentials saved!{RESET}")
            return True
        else:
            print(f"{YELLOW}⏭️  Skipped AWS{RESET}")
            return False
    
    def step_4_clarifai(self):
        """Clarifai registration (OPTIONAL)"""
        self.print_header("Step 4: Clarifai (5 minutes - OPTIONAL)")
        
        print(f"{YELLOW}🔗 Open this link:{RESET}")
        print(f"   https://clarifai.com/sign-up\n")
        
        print(f"📋 {YELLOW}Quick Setup:{RESET}")
        print(f"   1. Sign up with: {self.email}")
        print(f"   2. Go to: https://clarifai.com/settings/keys")
        print(f"   3. Click 'Generate New Key'")
        print(f"   4. Name: yourefuture-mvp")
        print(f"   5. Copy API Key and PAT\n")
        
        api_key = input(f"{BLUE}Clarifai API Key: {RESET}").strip()
        pat = input(f"{BLUE}Clarifai PAT: {RESET}").strip()
        
        if api_key and pat:
            self.env_vars['CLARIFAI_API_KEY'] = api_key
            self.env_vars['CLARIFAI_PAT'] = pat
            self.env_vars['CLARIFAI_APP_ID'] = 'main'
            self.env_vars['CLARIFAI_USER_ID'] = 'clarifai'
            print(f"{GREEN}✅ Clarifai credentials saved!{RESET}")
            return True
        else:
            print(f"{YELLOW}⏭️  Skipped Clarifai{RESET}")
            return False
    
    def step_5_tineye(self):
        """TinEye registration (TRIAL)"""
        self.print_header("Step 5: TinEye (5 minutes - TRIAL)")
        
        print(f"{YELLOW}🔗 Open this link:{RESET}")
        print(f"   https://tineye.com/solutions\n")
        
        print(f"📋 {YELLOW}Quick Setup:{RESET}")
        print(f"   1. Click 'Get API Access'")
        print(f"   2. Fill form with:")
        print(f"      - Email: {self.email}")
        print(f"      - Company: yourefuture")
        print(f"      - Use case: Deepfake detection and leak detection")
        print(f"   3. Submit request")
        print(f"   4. Wait for email (usually 24 hours)\n")
        
        api_key = input(f"{BLUE}TinEye API Key (if received): {RESET}").strip()
        api_secret = input(f"{BLUE}TinEye API Secret (if received): {RESET}").strip()
        
        if api_key and api_secret:
            self.env_vars['TINEYE_API_KEY'] = api_key
            self.env_vars['TINEYE_API_SECRET'] = api_secret
            print(f"{GREEN}✅ TinEye credentials saved!{RESET}")
            return True
        else:
            print(f"{YELLOW}⏭️  TinEye not ready yet (wait for email){RESET}")
            return False
    
    def step_6_feature_flags(self):
        """Configure feature flags"""
        self.print_header("Step 6: Feature Flags")
        
        self.env_vars['FEATURE_LEAK_CHECK_ENABLED'] = 'true'
        self.env_vars['FEATURE_IMAGE_ANALYSIS_ENABLED'] = 'true'
        self.env_vars['FEATURE_VIDEO_ANALYSIS_ENABLED'] = 'false'
        self.env_vars['FEATURE_REVERSE_IMAGE_SEARCH_ENABLED'] = 'false'
        
        # Default rate limits
        self.env_vars['LEAKCHECK_REQUESTS_PER_MINUTE'] = '20'
        self.env_vars['HUGGINGFACE_REQUESTS_PER_MINUTE'] = '10'
        self.env_vars['GOOGLE_VISION_REQUESTS_PER_MINUTE'] = '10'
        
        print(f"{GREEN}✅ Feature flags configured{RESET}")
        return True
    
    def verify_setup(self):
        """Verify all configured APIs"""
        self.print_header("Verification Summary")
        
        print(f"{BLUE}Configured APIs:{RESET}\n")
        
        # LeakCheck
        if self.env_vars.get('LEAKCHECK_API_KEY'):
            self.print_status('LeakCheck.io', '✅ Configured', GREEN)
        else:
            self.print_status('LeakCheck.io', '❌ Missing', RED)
        
        # Hugging Face
        if self.env_vars.get('HUGGINGFACE_API_KEY'):
            self.print_status('Hugging Face', '✅ Configured', GREEN)
        else:
            self.print_status('Hugging Face', '⚠️  Missing (NEEDED)', YELLOW)
        
        # Google Cloud
        if self.env_vars.get('GOOGLE_CLOUD_PROJECT_ID'):
            self.print_status('Google Cloud Vision', '✅ Configured', GREEN)
        else:
            self.print_status('Google Cloud Vision', '⚠️  Not configured', YELLOW)
        
        # AWS
        if self.env_vars.get('AWS_ACCESS_KEY_ID'):
            self.print_status('AWS Rekognition', '✅ Configured', GREEN)
        else:
            self.print_status('AWS Rekognition', '⏭️  Optional', BLUE)
        
        # Clarifai
        if self.env_vars.get('CLARIFAI_API_KEY'):
            self.print_status('Clarifai', '✅ Configured', GREEN)
        else:
            self.print_status('Clarifai', '⏭️  Optional', BLUE)
        
        # TinEye
        if self.env_vars.get('TINEYE_API_KEY'):
            self.print_status('TinEye', '✅ Configured', GREEN)
        else:
            self.print_status('TinEye', '⏭️  Trial pending', BLUE)
        
        print()
    
    def run(self):
        """Run registration workflow"""
        print(f"\n{BLUE}{'='*60}{RESET}")
        print(f"{BLUE}{'API Registration Helper':^60}{RESET}")
        print(f"{BLUE}Email: {self.email}{RESET}")
        print(f"{BLUE}{'='*60}{RESET}")
        
        print(f"\n{YELLOW}This script will guide you through API registration.{RESET}")
        print(f"{YELLOW}You can skip optional steps by pressing Enter.{RESET}")
        
        steps = [
            ('1. Hugging Face (CRITICAL)', lambda: self.step_1_huggingface()),
            ('2. Google Cloud (RECOMMENDED)', lambda: self.step_2_google_cloud()),
            ('3. AWS Rekognition (OPTIONAL)', lambda: self.step_3_aws()),
            ('4. Clarifai (OPTIONAL)', lambda: self.step_4_clarifai()),
            ('5. TinEye (TRIAL)', lambda: self.step_5_tineye()),
        ]
        
        for i, (name, step_func) in enumerate(steps):
            try:
                step_func()
            except KeyboardInterrupt:
                print(f"\n{YELLOW}⏹️  Registration cancelled{RESET}")
                return
            except Exception as e:
                print(f"{RED}❌ Error: {e}{RESET}")
        
        # Configure feature flags
        self.step_6_feature_flags()
        
        # Save and verify
        self.save_env()
        self.verify_setup()
        
        print(f"{GREEN}✅ All configurations saved to .env.local{RESET}\n")
        print(f"{BLUE}Next steps:{RESET}")
        print(f"  1. cd {self.workspace_root}")
        print(f"  2. pnpm install")
        print(f"  3. pnpm run dev")

if __name__ == '__main__':
    try:
        helper = APIRegistrationHelper()
        helper.run()
    except KeyboardInterrupt:
        print(f"\n{YELLOW}Registration cancelled{RESET}")
        sys.exit(0)
    except Exception as e:
        print(f"{RED}Fatal error: {e}{RESET}")
        sys.exit(1)
